# Generated by Django 6.0 on 2025-12-15 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_reports', models.IntegerField(default=0)),
                ('open_reports', models.IntegerField(default=0)),
                ('in_progress_reports', models.IntegerField(default=0)),
                ('resolved_reports', models.IntegerField(default=0)),
                ('closed_reports', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('average_resolution_time', models.IntegerField(default=0)),
                ('reports_created_today', models.IntegerField(default=0)),
                ('reports_resolved_today', models.IntegerField(default=0)),
                ('category_infrastructure', models.IntegerField(default=0)),
                ('category_environment', models.IntegerField(default=0)),
                ('category_health', models.IntegerField(default=0)),
                ('category_education', models.IntegerField(default=0)),
                ('category_transport', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statistiques Tableau de Bord',
                'verbose_name_plural': 'Statistiques Tableau de Bord',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('success', 'Succès')], default='info', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_users', models.ManyToManyField(blank=True, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Système',
                'verbose_name_plural': 'Notifications Système',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('report_created', 'Rapport créé'), ('report_updated', 'Rapport mis à jour'), ('report_commented', 'Commentaire ajouté'), ('file_uploaded', 'Fichier téléchargé'), ('profile_updated', 'Profil mis à jour')], db_index=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité Utilisateur',
                'verbose_name_plural': 'Activités Utilisateurs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='dashboard_u_user_id_0b0875_idx'), models.Index(fields=['activity_type', '-timestamp'], name='dashboard_u_activit_2da8d3_idx')],
            },
        ),
    ]
