# Generated by Django 6.0 on 2026-03-26 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_audit_and_notifications'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminnotification',
            new_name='dashboard_a_recipie_42ed76_idx',
            old_name='dashboard_a_recipie_idx',
        ),
        migrations.RenameIndex(
            model_name='adminnotification',
            new_name='dashboard_a_notific_2466b3_idx',
            old_name='dashboard_a_notifi_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='dashboard_a_actor_i_e1fbe9_idx',
            old_name='dashboard_a_actor_i_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='dashboard_a_action_bb96f4_idx',
            old_name='dashboard_a_action__idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='dashboard_a_target__3d9662_idx',
            old_name='dashboard_a_target_u_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='dashboard_a_target__ef1c07_idx',
            old_name='dashboard_a_target_r_idx',
        ),
    ]
