# Generated by Django 6.0 on 2026-03-26 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notification'),
        ('reports', '0003_remove_like_unique_report_user_like_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='accounts_no_recipie_799191_idx',
            old_name='accounts_not_recipie_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='accounts_no_recipie_646219_idx',
            old_name='accounts_not_recipie_read_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_notifications', to='reports.report'),
        ),
    ]
