# Generated by Django 6.0 on 2025-12-15 23:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('infrastructure', 'Infrastructure'), ('environment', 'Environnement'), ('health', 'Santé'), ('education', 'Éducation'), ('transport', 'Transports'), ('security', 'Sécurité'), ('other', 'Autre')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('in_progress', 'En cours'), ('resolved', 'Résolu'), ('closed', 'Fermé'), ('rejected', 'Rejeté')], db_index=True, default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique')], default='medium', max_length=20)),
                ('location', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('views_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('votes_count', models.IntegerField(default=0)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'moderator']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_assigned', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_authored', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/attachments/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'gif'])])),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.report')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pièce Jointe',
                'verbose_name_plural': 'Pièces Jointes',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.report')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Créé'), ('status_changed', 'Statut changé'), ('assigned', 'Assigné'), ('commented', 'Commenté'), ('attachment_added', 'Pièce jointe ajoutée'), ('updated', 'Mis à jour'), ('reopened', 'Rouvert')], max_length=50)),
                ('description', models.TextField()),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='reports.report')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique Rapport',
                'verbose_name_plural': 'Historiques Rapports',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReportVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField(choices=[(1, 'Utile'), (-1, 'Non utile')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='reports.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vote Rapport',
                'verbose_name_plural': 'Votes Rapports',
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-created_at'], name='reports_rep_status_7dd5e5_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['category', '-created_at'], name='reports_rep_categor_75c476_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['author', '-created_at'], name='reports_rep_author__2de601_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['assigned_to', 'status'], name='reports_rep_assigne_f77543_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['priority', 'status'], name='reports_rep_priorit_dbea92_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcomment',
            index=models.Index(fields=['report', '-created_at'], name='reports_rep_report__16f637_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcomment',
            index=models.Index(fields=['author', '-created_at'], name='reports_rep_author__b4c9e6_idx'),
        ),
        migrations.AddIndex(
            model_name='reporthistory',
            index=models.Index(fields=['report', '-timestamp'], name='reports_rep_report__dac67a_idx'),
        ),
        migrations.AddIndex(
            model_name='reporthistory',
            index=models.Index(fields=['action', '-timestamp'], name='reports_rep_action_99f7e5_idx'),
        ),
        migrations.AddIndex(
            model_name='reportvote',
            index=models.Index(fields=['report'], name='reports_rep_report__0f734e_idx'),
        ),
        migrations.AddIndex(
            model_name='reportvote',
            index=models.Index(fields=['user'], name='reports_rep_user_id_e3f60f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportvote',
            unique_together={('report', 'user')},
        ),
    ]
