# Generated by Django 6.0 on 2026-03-26 10:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_report_user_like',
        ),
        migrations.RenameIndex(
            model_name='like',
            new_name='reports_lik_report__b972e5_idx',
            old_name='reports_like_report_idx',
        ),
        migrations.RenameIndex(
            model_name='like',
            new_name='reports_lik_user_id_dfaaeb_idx',
            old_name='reports_like_user_idx',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('report', 'user')},
        ),
    ]
